; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = tbeam_v1_1_868

[env]
platform = espressif32
board = ttgo-t-beam
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps = 
    jgromes/RadioLib@^6.0.0
    fbiego/ESP32Time@^2.0.0
    lewisxhe/XPowersLib @ ^0.2.6
    mikalhart/TinyGPSPlus @ ^1.0.3

[env:tbeam_v1_1_868]
build_flags = 
    -D WASP_BOARD_V1_1
    -D _DEFAULT_SOURCE

[env:tbeam_v1_2_868]
build_flags = 
    -D WASP_BOARD_V1_2
    -D _DEFAULT_SOURCE

[env:tbeam_v1_1_433]
build_flags = 
    -D WASP_BOARD_V1_1
    -D FREQ_433
    -D _DEFAULT_SOURCE

[env:tbeam_v1_2_433]
build_flags = 
    -D WASP_BOARD_V1_2
    -D FREQ_433
    -D _DEFAULT_SOURCE